language: swift
osx_image: xcode10
script: echo "Hello World"
before_install:
  - gem install fastlane --no-ri --no-rdoc --no-document

install: true
script:
- xcodebuild -project Mahjong.xcodeproj/ -target Mahjong -destination 'platform=iOS Simulator,OS=12.0,name=iPhone X' clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
